// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCm_3eSCHS2bAdCAnFj7faK2_PSSbu8Hk',
    appId: '1:158363147016:web:da7ed6e6815614823baabd',
    messagingSenderId: '158363147016',
    projectId: 'zapys-rafael-rarvs',
    authDomain: 'zapys-rafael-rarvs.firebaseapp.com',
    storageBucket: 'zapys-rafael-rarvs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3o6XOeAdJ9JDUdKX5iTz32Y80GZmPgHw',
    appId: '1:158363147016:android:3f7c1f331c22ded53baabd',
    messagingSenderId: '158363147016',
    projectId: 'zapys-rafael-rarvs',
    storageBucket: 'zapys-rafael-rarvs.appspot.com',
  );
}
